#!/bin/bash

if ! [ -x "$(command -v js-beautify)" ]; then
	# https://pypi.org/project/jsbeautifier/
	sudo pip install jsbeautifier
fi

if ! [ -x "$(command -v tidy)" ]; then
	# https://github.com/htacg/tidy-html5
	sudo apt install tidy-html5
fi

unminify () {
	echo "'../$1'  =>  '$1'"
	js-beautify --disable-preserve-newlines -o $1 ../$1
}

unminify_html () {
	echo "'../$1'  =>  '$1'"
	tidy --indent yes -quiet --show-warnings false -output $1 ../$1
}


unminify_html background.html
unminify_html options.html
unminify sieve.jsn
unminify locales.jsn

mkdir -p includes
unminify includes/app.js
unminify includes/content.js

mkdir -p js
unminify js/app_bg.js
unminify js/background.js
unminify js/options.js
unminify js/SieveUI.js
